### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by sreilly** [violetlib/vaqua#7]
I'm having a bit of trouble getting started building vaqua and was hoping you might have a quick answer to get me past my current block. What is supposed to be contained in the library.xml file which is imported into all of the build.xml files? It's path is one level above the repository.

A couple of other issues that slowed me down building was that 1) the full path to the java_home exe was needed in the build.xml and 2) the "fork" parameters in the javac tasks broke the builds.

If I can get this building I'd be happy to provide a PR that helps others get up to speed faster.

**Comment by cbfiddle** [comment]
I assume you are referring to the build.xml files under Java8Support and Java9Support?
I believe those should not be needed and probably should not be in the repo.
The same is true for the top level build.xml.
The release/build.xml is the one to use.

Regarding java_home, I had to remove the absolute path because Apple broke java_home in Big Sur and being protected it cannot be patched.
If you are not using Big Sur, then just add the path to $PATH.

Otherwise, try something like this:

#!/bin/sh

# Emulate the required features of java_home, which is broken on macOS 11.

FAIL=0

if test "$1" = "-F"
then
  FAIL=1
  shift
fi

if test "$1" = "-v"
then
  shift
else
  echo "Unsupported arguments: expects -F -v <version>"
  exit 1
fi

if test "$1" = "1.8"
then
  echo "/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home"
  exit 0
fi

echo "/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home"
exit 0


Tell me more about the “fork” problem.
Is it because javac has changed or ant has changed?

  Alan

**Comment by sreilly** [comment]
Hi Alan, thanks for all of the help. I've removed the Java8Support and Java9Support folders that that helps a lot.

I am running big sur and simply removing the -F flag seems to work properly, so I've done that for now.

As for the fork problem, I think it was a change in ant that happened years ago but maybe it is related to the version of javac being used. I only vaguely remember making the change to remove the "fork" attribute in my own projects because it happened so long ago. Anyway, I haven't noticed any adverse effects to removing it.

I've also setup my repos to use git submodules for the jnr and vappearance repositories rather than using maven or ivy.  It's a personal preference, but it allows me to tweak settings and get all three repositories building without needing maven which would've pulled down your copies of the jnr and vappearance. Plus, I know basically nothing about maven or ivy.

Is there currently a benefit to having the three separate repositories? Combining them would have made it easier for me to get started, but maybe there's an advantage I'm not seeing. I'm really excited about using vaqua in my own app's next update.

Thanks,
Sean

**Comment by cbfiddle** [comment]
What was the change needed to generate fat binaries?

**Comment by cbfiddle** [comment]
java_home is still broken on Ventura when -F is used with a pattern like "9+".
Removing the -F is fine as long as there is a 9+ version on the system, which is highly likely.
I do not see any problem using fork=true. If you are still having a problem, please open a new issue.
